name: Build DLL

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Upload DLL
        uses: actions/upload-artifact@v3
        with:
          name: SLA-Cheeto-DLL
          path: build/Release/*.dll
