name: Build

on:
  push:
    branches: [ main ]

env:
  # SOLUTION_FILE_PATH: ./SoloLevelling.sln
  PROJECT_FILE_PATH: ./cheat/SoloLevelling.vcxproj
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: |
        msbuild ${{ env.PROJECT_FILE_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.PLATFORM }}  

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build-artifact
        path: ./cheat/bin/Release-x64/SLA_Cheeto.dll
        if-no-files-found: error
